defmodule Tunez.Repo.Migrations.CreateAlbumsArtistIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:albums, "albums_artist_id_fkey")

    alter table(:albums) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "albums_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create_if_not_exists index(:albums, [:artist_id])
  end

  def down do
    drop_if_exists index(:albums, [:artist_id])

    drop constraint(:albums, "albums_artist_id_fkey")

    alter table(:albums) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "albums_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
